using Microsoft.EntityFrameworkCore.Migrations;

namespace Vega.Migrations
{
    public partial class SeedDatabase : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Acura')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Alfa Romeo')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Aptera')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Aston Martin')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Audi')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Austin')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Bentley')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('BMW')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Bugatti')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Buick')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Cadillac')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Chevrolet')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Chrysler')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Citroën')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Corbin')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Daewoo')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Daihatsu')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Dodge')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Eagle')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Fairthorpe')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Ferrari')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('FIAT')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Fillmore')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Foose')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Ford')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Geo')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('GMC')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Hillman')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Holden')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Honda')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('HUMMER')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Hyundai')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Infiniti')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Isuzu')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Jaguar')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Jeep')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Jensen')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Kia')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Lamborghini')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Land Rover')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Lexus')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Lincoln')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Lotus')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Maserati')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Maybach')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Mazda')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('McLaren')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Mercedes-Benz')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Mercury')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Merkur')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('MG')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('MINI')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Mitsubishi')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Morgan')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Nissan')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Oldsmobile')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Panoz')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Peugeot')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Plymouth')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Pontiac')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Porsche')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Ram')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Rambler')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Renault')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Rolls-Royce')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Saab')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Saturn')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Scion')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Shelby')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Smart')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Spyker')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Spyker Cars')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Studebaker')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Subaru')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Suzuki')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Tesla')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Toyota')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Volkswagen')");
            migrationBuilder.Sql("INSERT INTO Makes (Name) VALUES ('Volvo')");


            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '5000S', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '4000s', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Quattro', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '5000S', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Coupe GT', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '5000CS Quattro', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '4000s Quattro', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '4000CS Quattro', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '4000', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '5000CS', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '90', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '80/90', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '80', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '100', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '200', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'V8', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Coupe Quattro', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'S4', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Cabriolet', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'riolet', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'S6', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'A6', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'A4', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'A8', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'TT', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'S8', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Allroad', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'RS6', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'RS 6', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'A3', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Q7', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'RS4', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'RS 4', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'S5', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'R8', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'A5', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Q5', (SELECT ID FROM Makes WHERE Name = 'Audi'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'A7', (SELECT ID FROM Makes WHERE Name = 'Audi'))");


            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '600', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '6 Series', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '3 Series', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '5 Series', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '7 Series', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '8 Series', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'M5', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'M3', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Z3', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'X5', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'M', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Z8', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '525', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '530', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '745', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '760', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Z4', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '325', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '545', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '645', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'X3', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '330', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '550', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '650', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '750', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'M6', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'M Roadster', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Z4 M', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Alpina B7', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '1 Series', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'X6', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Z4 M Roadster', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'X5 M', (SELECT ID FROM Makes WHERE Name = 'BMW'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'X6 M', (SELECT ID FROM Makes WHERE Name = 'BMW'))");


            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'W123', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'W126', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'S-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'E-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'W201', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'SL-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '190E', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '300CE', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '300D', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '300E', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '300SD', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '300SE', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '300SL', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '300TE', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '400E', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '400SE', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '500E', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '500SEL', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '500SL', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '600SEL', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'C-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '400SEL', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '500SEC', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '600SEC', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( '600SL', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'SLK-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'M-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'CL-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'CLK-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'G-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'SLR McLaren', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'CLS-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'G55 AMG', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'SL65 AMG', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'R-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'GL-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'SLK55 AMG', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'CL65 AMG', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Sprinter', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'GLK-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'SLS AMG', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'SLS-Class', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Sprinter 2500', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Sprinter 3500', (SELECT ID FROM Makes WHERE Name = 'Mercedes-Benz'))");


            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Beetle', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Golf', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Jetta', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Vanagon', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Scirocco', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Quantum', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'GTI', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Cabriolet', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Passat', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Type 2', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Fox', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Corrado', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Eurovan', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'riolet', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Golf III', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Jetta III', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'rio', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'New Beetle', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Touareg', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'R32', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Phaeton', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Rabbit', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Eos', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'GLI', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Touareg 2', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'CC', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Tiguan', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
            migrationBuilder.Sql("INSERT INTO Models (Name, MakeID) VALUES ( 'Routan', (SELECT ID FROM Makes WHERE Name = 'Volkswagen'))");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM Makes WHERE Name IN ('Audi', 'BMW', 'Mercedes-Benz', 'Volkswagen')");
        }
    }
}
